config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
  resources :comments, only: [:create,:destroy,:update]
end
  devise_for :users
  	

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true
	before_save :set_visits_count

    
    def update_visits_count
    	self.update(visits_count: self.visits_count + 1)
    	
    end


    private
    def set_visits_count
    	self.visits_count ||= 0
    	
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show,:index]
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	#GET /articles
	def index
	@articles =	Article.all
	end	
	#GET /articles/:id
	def show 
	@articles.update_visits_count
	@comment = Comment.new	
	end
	#GET  /articles/new
	def new
	  @articles = Article.new	
	end 
	#POST /articles
	def create
	 @articles = current_user.articles.new(article_params)
	 if @articles.save	
	 redirect_to @articles	
	 else
	render:new
	end
end
	def destroy
		@articles = Article.find(params[:id])
		@articles.destroy
		 redirect_to articles_path	
	end

	def edit
		@articles = Article.find(params[:id])
	end

	def update
		@articles = Article.find(params[:id])
		if @articles.update(article_params)
			redirect_to @articles
		else
		render :edit	
		end

	end

	private

	def article_params
		params.require(:article).permit(:title,:body)
		
	end

	def set_article
      @articles = Article.find(params[:id])
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
  before_action :authenticate_user! 


  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @articles
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @articles, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @articles = Article.find(params[:article_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<h1><%= name %> articulo</h1>
<%=form_for(@articles) do |f|%>
 <% @articles.errors.full_messages.each do |message| %>
  <div class="be-red white top-space">
	*<%=message%>
  </div>
 <%end%>
  <div class="field">
    <%= f.text_field :title, placeholder: "Titulo", class: "form-control"%>
	
  </div>
  <div class="field">
	<%=f.text_area :body, placeholder: "Escribe aqui el Articulo", style:"height:250px;", class: "form-control"%>
  </div>

  <div class="field">
  	<%= f.submit "Guardar", class: "be-red white" %>
  </div>
<%end%> 

app/views/articles/edit.html.erb
 <div style="width:80%;margin:0 auto;"> 
<%= render "form", name: "Editar"%>
</div>

app/views/articles/index.html.erb
<main>

        <!--Main layout-->
        <div class="container">

            <!--Page heading-->
            <div class="row">
                <div class="col-md-12">
                    <h1 class="h1-responsive">Artículos Publicados
                        <small class="text-muted">más vistos</small>
                    </h1>
                </div>
            </div>
            <!--/.Page heading-->
            <hr>

            <!--First row-->
            
            <div class="row">
            <% @articles.each do |article|%>
                <!--First column-->
                <div class="col-lg-4">
                <br/><br/>		
                    <!--Card-->
                    <div class="card">
                        <!--Card image-->
                        <div class="view overlay hm-white-slight">
                            <img src="http://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(13).jpg" class="img-fluid" alt="">
                            <a href="#!">
                                <div class="mask"></div>
                            </a>
                        </div>
                        <!--/.Card image-->

                        <!--Card content-->
                        <div class="card-block">
                            <!--Title-->
                            
                            <h4 class="card-title"><%= article.title %></h4>
                            <!--Text-->
                            <p class="card-text"><%= article.body %></p>
                             
                             <%= link_to "Eliminar", article, method: :delete%>

                            <div class="read-more">
                                <a href="article" class="btn btn-primary waves-effect waves-light">Read more</a>
                                <%= link_to "Show",article %>
                                <a href="article" class="btn btn-raised btn-primary">Primary</a>
                            </div>
                        </div>
                        <!--/.Card content-->

                    </div>
                    <!--/.Card-->
                </div>
                <!--/.First column-->
              <%end%>
            </div>  
            <br/><br/>  
<%= link_to 'Nuevo Articulo', new_article_path %>
            <hr>

            <!--Pagination-->
            <nav class="row flex-center">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <a class="page-link waves-effect waves-effect" href="#!" aria-label="Previous">
                            <span aria-hidden="true">«</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link waves-effect waves-effect" href="#!">1 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="page-item"><a class="page-link waves-effect waves-effect" href="#!">2</a></li>
                    <li class="page-item"><a class="page-link waves-effect waves-effect" href="#!">3</a></li>
                    <li class="page-item"><a class="page-link waves-effect waves-effect" href="#!">4</a></li>
                    <li class="page-item"><a class="page-link waves-effect waves-effect" href="#!">5</a></li>
                    <li class="page-item">
                        <a class="page-link waves-effect waves-effect" href="#!" aria-label="Next">
                            <span aria-hidden="true">»</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <!--/.Pagination-->
        </div>
        <!--/.Main layout-->
    </main>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
 <%= render "form", name: "Crear"%>	
</div>
  

app/views/articles/show.html.erb
<h1><%= @articles.title %></h1>
<% unless @articles.user.nil?%>
<p>
	Escrito por: <%= @articles.user.email%>
</p>
<%end%>
<p>
	Visitas: <%= @articles.visits_count %>
</p>
<div>
	<%= @articles.body%>
</div>
<div class="field">
	<h3> Comentarios</h3>
	<%= render "comments/form"%>
	<ul>
		<%@articles.comments.each do |comment|%>
		<li> 
			<%= comment.body%>  -  <%=comment.user.email%> 
		</li>
		<%end%>
	</ul>
</div>
<br/> <br/>
<%= link_to "Articulos" , articles_path%> - <%= link_to "Editar Articulo", edit_article_path(@articles) %> 

app/views/comments/_form.html.erb
<%= form_for([@articles,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
  
  <%=render "partials/navigation"%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
    <%=render "partials/footer"%>
  </body>
</html>
   

app/views/partials/_footer.html.erb
<footer class="page-footer center-on-small-only primary-color-dark">
        <!--Footer links-->
        <div class="container-fluid">
            <div class="row">
                <!--First column-->
                <div class="col-md-3 offset-lg-1 hidden-lg-down">
                    <h5 class="title">About material design</h5>
                    <p>Material Design (codenamed Quantum Paper) is a design language developed by Google.</p>
                    <p>Material Design for Bootstrap (MDB) is a powerful Material Design UI KIT for most popular HTML, CSS, and JS framework - Bootstrap.</p>
                </div>
                <!--/.First column-->
                <hr class="hidden-md-up">
                <!--Second column-->
                <div class="col-lg-2 col-md-4 offset-lg-1">
                    <h5 class="title">First column</h5>
                    <ul>
                        <li>
                            <a href="#!">Link 1</a>
                        </li>
                        <li>
                            <a href="#!">Link 2</a>
                        </li>
                        <li>
                            <a href="#!">Link 3</a>
                        </li>
                        <li>
                            <a href="#!">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--/.Second column-->
                <hr class="hidden-md-up">
                <!--Third column-->
                <div class="col-lg-2 col-md-4">
                    <h5 class="title">Second column</h5>
                    <ul>
                        <li>
                            <a href="#!">Link 1</a>
                        </li>
                        <li>
                            <a href="#!">Link 2</a>
                        </li>
                        <li>
                            <a href="#!">Link 3</a>
                        </li>
                        <li>
                            <a href="#!">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--/.Third column-->
                <hr class="hidden-md-up">
                <!--Fourth column-->
                <div class="col-lg-2 col-md-4">
                    <h5 class="title">Third column</h5>
                    <ul>
                        <li>
                            <a href="#!">Link 1</a>
                        </li>
                        <li>
                            <a href="#!">Link 2</a>
                        </li>
                        <li>
                            <a href="#!">Link 3</a>
                        </li>
                        <li>
                            <a href="#!">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--/.Fourth column-->
            </div>
        </div>
        <!--/.Footer links-->
        <hr>
        <!--Call to action-->
        <div class="call-to-action">
            <h4>Material Design for Bootstrap</h4>
            <ul>
                <li>
                    <h5>Get our UI KIT for free</h5>
                </li>
                <li>
                    <a target="_blank" href="http://mdbootstrap.com/getting-started/" class="btn btn-danger waves-effect waves-light">Sign up!</a>
                </li>
                <li>
                    <a target="_blank" href="http://mdbootstrap.com/material-design-for-bootstrap/" class="btn btn-default waves-effect waves-light">Learn more</a>
                </li>
            </ul>
        </div>
        <!--/.Call to action-->

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="containter-fluid">
                © 2015 Copyright: <a href="http://www.MDBootstrap.com"> MDBootstrap.com </a>
            </div>
        </div>
        <!--/.Copyright-->
    </footer>

app/views/partials/_navigation.html.erb
<div class="bs-component">
          <div class="navbar navbar-warning">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-warning-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="javascript:void(0)">Brand</a>
              </div>
              <div class="navbar-collapse collapse navbar-warning-collapse">
                <ul class="nav navbar-nav">
                  <li class="active"><%= link_to "Inicio",root_path %></li>
                  <li><a href="javascript:void(0)">Link</a></li>
                  <li class="dropdown">
                    <a href="http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown
                      <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="javascript:void(0)">Action</a></li>
                      <li><a href="javascript:void(0)">Another action</a></li>
                      <li><a href="javascript:void(0)">Something else here</a></li>
                      <li class="divider"></li>
                      <li class="dropdown-header">Dropdown header</li>
                      <li><a href="javascript:void(0)">Separated link</a></li>
                      <li><a href="javascript:void(0)">One more separated link</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="navbar-form navbar-left">
                  <div class="form-group is-empty">
                    <input class="form-control col-md-8" placeholder="Search" type="text">
                  </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                  <li><%=link_to "Cerrar sesion", destroy_user_session_path, method: :delete%></li>
                  <li><%=link_to "Iniciar sección", new_user_session_path%></li>
                  <li><%=link_to "Crear cuenta", new_user_registration_path  %></li>
                  <li class="dropdown">
                    <a href="http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown
                      <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="javascript:void(0)">Action</a></li>
                      <li><a href="javascript:void(0)">Another action</a></li>
                      <li><a href="javascript:void(0)">Something else here</a></li>
                      <li class="divider"></li>
                      <li><a href="javascript:void(0)">Separated link</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<h1>Bienvenido <%= current_user.email %></h1>
<%end%>
<%= link_to "Articulos", articles_path %>